In [ ]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.11/dist-packages (0.2.65)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.3.8)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.13.4)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.12.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.14.1)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.11/dist-packages (from curl_cffi>=0.7->yfinance) (2025.7.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [ ]:
import os
import warnings
import numpy as np
import pandas as pd
from scipy.stats import gmean
import yfinance as yf
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta, date, time
warnings.filterwarnings('ignore')

In [ ]:
tickers = ['SPY',"NVDA", "MSFT", "AAPL", "AMZN", "GOOGL", "META", "AVGO", "BRK-B", "TSLA", "JPM",
    "WMT", "LLY", "V", "ORCL", "NFLX", "MA", "XOM", "COST", "PG", "JNJ",
    "HD", "BAC", "ABBV", "PLTR", "KO", "UNH", "PM", "TMUS", "CSCO", "WFC",
    "CRM", "GE", "AMD", "DOW", "NKE", "MCD", "PFE", "TXN", "MRK", "IBM",
    "ADBE", "INTC", "T", "UPS", "AMGN", "QCOM", "VZ", "SO", "BMY", "HON",
    "LIN", "CVX", "CAT", "GS", "NEE", "LOW", "SPGI", "MS", "BLK", "RTX",
    "NOW", "SCHW", "BA", "ISRG", "CI", "MDT", "DE", "ELV", "AXP", "INTU",
    "ADP", "CB", "TJX", "PYPL", "C", "ZTS", "PGR", "DUK", "MMC", "LMT",
    "VRTX", "SYK", "TMO", "BDX", "MO", "ADI", "REGN", "BKNG", "ICE", "ABNB",
    "FDX", "GM", "NSC", "FIS", "HUM", "CL", "GILD", "WM", "EW", "AON",
    "ROST", "DHR", "PNC", "ETN", "ITW", "SHW", "CSX", "MNST", "TRV", "EMR",
    "AEP", "ALL", "GD", "PSX", "HCA", "MCO", "MAR", "APD", "EOG", "LRCX",
    "KLAC", "PCAR", "CDNS", "MCK", "CTAS", "ORLY", "AFL", "STZ", "ANET", "FTNT",
    "KHC", "PAYX", "PH", "MTD", "CTSH", "TGT", "AZO", "IDXX", "TT", "SRE",
    "WELL", "DLR", "F", "CME", "ED", "MRNA", "CMI", "NEM", "HSY",
    "WBA", "TEL", "ODFL", "BIIB", "HPQ", "CARR", "AME", "COF", "HES", "D",
    "AIG", "A", "MSI", "EXC", "RSG", "YUM", "HIG", "O", "XEL", "TSCO",
    "CHD", "KEYS", "FAST", "EFX", "TDG", "ACN", "BKR", "CEG", "GPN",
    "KMB", "AVB", "VRSK", "CDW", "HLT", "CMS", "ROL", "NUE", "ATO",
    "VLO", "ZBH", "QRVO", "IP", "MTB", "FTV", "ULTA", "MLM", "LH", "HOLX",
    "INCY", "WAT", "XYL", "LUV", "NVR", "SJM", "PPG", "NDAQ", "DRI"]
# List of companies
df = pd.DataFrame(yf.download(tickers, start='2015-01-01', end='2025-08-01', interval="1d")['Close'])

[*********************100%***********************]  207 of 207 completed

In [ ]:
return_daily = df.pct_change()

In [ ]:
sharpe_daily =return_daily.rolling(window=252).mean()/return_daily.rolling(window=252).std()
sharpe_daily =sharpe_daily.dropna()
sharpe_daily

Ticker,A,AAPL,ABBV,ABNB,ACN,ADBE,ADI,ADP,AEP,AFL,...,WELL,WFC,WM,WMT,XEL,XOM,XYL,YUM,ZBH,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-20,0.030859,-0.020731,0.045465,-0.025141,-0.025808,-0.038036,0.016938,0.024946,0.021834,0.047248,...,-0.019466,-0.030039,0.005886,0.006613,0.016453,0.097537,0.016188,0.016996,0.018751,-0.028446
2023-01-23,0.035614,-0.014741,0.048104,-0.023352,-0.025994,-0.033026,0.026255,0.032950,0.024351,0.052806,...,-0.016218,-0.023207,0.010438,0.014576,0.014079,0.096176,0.005199,0.018945,0.022218,-0.026217
2023-01-24,0.034319,-0.010729,0.048702,-0.023593,-0.025131,-0.031449,0.024485,0.034514,0.024318,0.061986,...,-0.018372,-0.021098,0.013114,0.016923,0.015227,0.100684,0.007936,0.021410,0.022304,-0.025645
2023-01-25,0.033611,-0.010701,0.048512,-0.017471,-0.028263,-0.038398,0.022016,0.022770,0.025836,0.060376,...,-0.017637,-0.016015,0.017740,0.015785,0.019246,0.098165,0.005402,0.018424,0.019465,-0.025841
2023-01-26,0.038834,-0.006093,0.045844,-0.010073,-0.025208,-0.030803,0.030494,0.021648,0.028135,0.058096,...,-0.015439,-0.015002,0.020024,0.020757,0.018394,0.099830,0.009385,0.027310,0.025071,-0.017838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-07-25,-0.006179,0.000668,0.038095,0.005190,-0.023397,-0.060165,0.013682,0.085213,0.069931,0.038311,...,0.125592,0.080391,0.026233,0.094461,0.102520,0.009587,-0.004240,0.054748,-0.017627,-0.028952
2025-07-28,-0.012897,0.006574,0.032084,0.010740,-0.027207,-0.055907,0.019464,0.085003,0.059585,0.031958,...,0.119201,0.078229,0.025739,0.095026,0.089094,0.008378,0.002387,0.051075,-0.022574,-0.031503
2025-07-29,-0.013649,0.004936,0.027860,0.009462,-0.026656,-0.055676,0.021988,0.083629,0.060556,0.031852,...,0.133168,0.076434,0.066650,0.099158,0.091316,0.006283,0.001028,0.050189,-0.025278,-0.032581
2025-07-30,-0.020372,0.002405,0.021904,0.007062,-0.029534,-0.062628,0.018443,0.082087,0.069308,0.023580,...,0.130648,0.072244,0.067339,0.098036,0.088922,0.004241,-0.008520,0.051625,-0.030656,-0.034839
2025-07-31,-0.026071,0.000736,0.025549,0.004217,-0.033674,-0.063800,0.013457,0.077241,0.066968,0.026530,...,0.123757,0.072082,0.056263,0.099689,0.091459,0.006370,0.016206,0.040831,-0.033741,-0.042369

In [ ]:
sharpe_monthly = sharpe_daily.resample('ME').last()
# Get the column names for the 10 highest values in each row
top_10_columns = pd.DataFrame(sharpe_monthly.apply(lambda x: x.nlargest(10).index.tolist(), axis=1))

# Get the column names for the 10 lowest values in each row
bottom_10_columns = pd.DataFrame(sharpe_monthly.apply(lambda x: x.nsmallest(10).index.tolist(), axis=1))
top_columns = top_10_columns.merge(bottom_10_columns, left_index= True, right_index = True, how = 'outer')
top_columns.columns = ['top_10', 'bottom_10']
top_columns

,top_10,bottom_10
Date,,
2023-01-31,"[MCK, MRK, CEG, XOM, VLO, LLY, NUE, HES, CI, T...","[INTC, PYPL, AVB, CHD, META, WBA, FIS, VZ, CME..."
2023-02-28,"[MRK, CEG, GILD, PGR, XOM, VLO, MCK, AZO, ULTA...","[INTC, D, VZ, AVB, NEM, GOOGL, CTSH, AMZN, CME..."
2023-03-31,"[GILD, MRK, MNST, ULTA, XOM, PCAR, VLO, TJX, H...","[D, AVB, BAC, SCHW, PNC, MDT, FIS, NEM, CTSH, ..."
2023-04-30,"[MRK, GE, LLY, GILD, PCAR, NFLX, XOM, MSI, MCD...","[D, LUV, IP, NEM, DLR, FIS, PFE, AVB, NSC, CTSH]"
2023-05-31,"[GE, ORLY, NFLX, ORCL, NVDA, BA, CDNS, HSY, MN...","[D, IP, VZ, PFE, NEM, LUV, FIS, PNC, WBA, MTB]"
2023-06-30,"[GE, ORCL, TDG, NFLX, ORLY, NVDA, HCA, PCAR, A...","[D, PFE, VZ, FIS, WBA, BMY, INCY, NEM, T, IP]"
2023-07-31,"[GE, NVDA, ORCL, AVGO, TJX, PCAR, TDG, NFLX, B...","[D, PFE, VZ, INCY, FIS, WAT, BMY, WBA, O, EW]"
2023-08-31,"[GE, NVDA, LLY, ETN, TJX, AVGO, ORCL, BKNG, PH...","[D, XEL, PFE, AEP, FIS, MTB, NEE, WBA, PYPL, O]"
2023-09-30,"[GE, NVDA, FDX, BKNG, TJX, ORCL, AVGO, PCAR, E...","[D, NEE, PFE, BMY, WBA, PYPL, TGT, MTB, AEP, I..."
2023-10-31,"[META, GE, NVDA, AVGO, LLY, FDX, CDNS, BKNG, A...","[D, BMY, PFE, WBA, LUV, INCY, SJM, HSY, MRNA, ..."
2023-11-30,"[META, GE, NVDA, TDG, ADBE, AVGO, CDNS, MSFT, ...","[BMY, WBA, PFE, SJM, INCY, MRNA, LUV, NEE, HSY..."
2023-12-31,"[META, GE, NVDA, CRM, BKNG, AVGO, TDG, COST, A...","[PFE, BMY, HSY, MRNA, SJM, NEE, INCY, D, WBA, ..."
2024-01-31,"[NVDA, META, LLY, AVGO, RSG, GE, MSFT, TDG, CO...","[PFE, BMY, INCY, WBA, NEM, MRNA, D, O, MTD, NEE]"
2024-02-29,"[LLY, META, GE, NVDA, COST, CEG, RSG, AVGO, CR...","[PFE, BMY, HSY, WBA, INCY, HUM, BIIB, SJM, NEM..."
2024-03-31,"[LLY, RSG, GE, PCAR, CEG, TDG, NVDA, JPM, BRK-...","[PFE, HSY, HUM, WBA, BIIB, BMY, SJM, INCY, NEM..."
2024-04-30,"[GE, CEG, ETN, TDG, NVDA, LLY, RSG, MLM, PH, TT]","[BMY, HUM, HSY, WBA, PFE, BIIB, INCY, SJM, NKE..."
2024-05-31,"[TT, TDG, GE, CEG, ETN, COST, NVDA, JPM, HIG, GD]","[BMY, WBA, HSY, BIIB, SJM, HUM, PFE, GILD, UPS..."
2024-06-30,"[COST, NVDA, GE, LLY, TT, JPM, REGN, HLT, CEG,...","[BMY, WBA, HSY, ZBH, SJM, NKE, UPS, PFE, BIIB,..."
2024-07-31,"[HIG, PGR, MCK, GE, CTAS, COST, REGN, TMUS, TT...","[WBA, UPS, NKE, ZBH, SJM, BIIB, BMY, BA, BDX, ..."
2024-08-31,"[PGR, HIG, COST, TMUS, ALL, CL, RSG, MSI, CTAS...","[WBA, BIIB, MNST, UPS, BA, HUM, SJM, INTC, BDX..."
2024-09-30,"[CTAS, MSI, RTX, PGR, TMUS, HIG, CL, GE, ALL, ...","[WBA, HUM, BIIB, BA, INTC, CVX, MRNA, HES, BDX..."
2024-10-31,"[TMUS, MSI, FIS, AXP, CTAS, WELL, TT, SPY, BLK...","[HUM, WBA, BIIB, INTC, NKE, BA, ELV, MRNA, BDX..."
2024-11-30,"[WMT, TMUS, TT, COST, CTAS, MSI, WELL, AXP, PG...","[BIIB, WBA, HUM, INTC, BA, NKE, MRNA, CDW, QRV..."
2024-12-31,"[WMT, PLTR, MSI, NFLX, NVDA, PGR, AXP, WELL, T...","[BIIB, WBA, INTC, HUM, DOW, MRNA, PPG, NUE, BA..."
2025-01-31,"[WMT, PLTR, WELL, GE, MSI, RTX, GS, TMUS, PM, ...","[BIIB, REGN, INTC, DOW, MRNA, STZ, NUE, PPG, H..."
2025-02-28,"[WELL, T, WMT, PM, TMUS, MO, RTX, PLTR, ATO, N...","[BIIB, MRNA, DOW, REGN, MRK, STZ, AMD, ULTA, C..."
2025-03-31,"[WELL, T, PM, TMUS, MO, PLTR, GILD, ATO, WMT, ...","[DOW, MRNA, BIIB, REGN, CDW, MRK, STZ, NUE, TG..."
2025-04-30,"[PM, PLTR, T, WELL, NFLX, GILD, MO, ATO, WMT, ...","[BIIB, MRNA, DOW, MRK, REGN, HOLX, UPS, CDW, T..."
2025-05-31,"[PLTR, PM, T, GILD, WELL, CME, ATO, NFLX, RSG,...","[MRNA, DOW, BIIB, REGN, MRK, TMO, UNH, STZ, NU..."
2025-06-30,"[PLTR, PM, NFLX, CME, T, IBM, WELL, GILD, CSCO...","[BIIB, MRNA, REGN, MRK, DOW, STZ, TMO, ELV, BD..."
2025-07-31,"[PLTR, CME, NFLX, WELL, T, CSCO, SCHW, NDAQ, G...","[MRNA, BIIB, REGN, DOW, ELV, UNH, MRK, STZ, AD..."

In [ ]:
return_monthly = return_daily.resample('ME').last().reset_index()
return_monthly

Ticker,Date,A,AAPL,ABBV,ABNB,ACN,ADBE,ADI,ADP,AEP,...,WELL,WFC,WM,WMT,XEL,XOM,XYL,YUM,ZBH,ZTS
0,2015-01-31,-0.017941,-0.014634,-0.043885,NaN,-0.018800,-0.021078,-0.021041,-0.021577,-0.014281,...,-0.021376,-0.015921,-0.021313,-0.031236,-0.015219,-0.001827,-0.001757,-0.026794,-0.003732,-0.013620
1,2015-02-28,-0.003541,-0.015028,-0.000330,NaN,-0.002990,0.001773,-0.005775,0.000000,0.002961,...,0.013672,-0.006528,0.003685,0.001552,-0.003952,-0.001242,-0.001956,0.021665,-0.007748,-0.011369
2,2015-03-31,-0.004075,-0.015352,0.005151,NaN,-0.007731,0.004620,-0.027928,-0.002911,-0.005832,...,-0.017151,-0.006755,0.004073,-0.003393,0.002015,-0.007357,-0.009335,-0.008689,-0.008856,-0.013426
3,2015-04-30,-0.014061,-0.027130,-0.014780,NaN,-0.010678,-0.007697,-0.015600,-0.009954,-0.015920,...,-0.026230,-0.006492,-0.007017,0.002183,-0.017671,-0.005690,0.010647,-0.003362,-0.047685,-0.017691
4,2015-05-31,-0.013413,-0.011383,-0.013042,NaN,-0.008977,-0.011622,-0.005124,-0.005350,0.003387,...,-0.008048,-0.004448,-0.002812,-0.007616,-0.002344,0.001057,-0.003542,-0.018410,0.006173,0.013439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,2025-03-31,0.002485,0.019413,0.020605,-0.010191,0.025334,-0.005652,0.000546,0.015623,0.021597,...,-0.001369,0.015561,0.015751,0.031004,0.015347,0.010193,0.000167,0.010272,0.010355,0.009441
123,2025-04-30,0.001303,0.006108,0.008217,-0.028448,0.002278,0.010782,0.011678,0.016330,-0.001475,...,0.007328,-0.001266,0.019930,0.012599,0.000425,-0.025194,0.016439,0.018620,0.002529,0.006241
124,2025-05-31,-0.012006,0.004501,0.002640,0.004986,-0.002864,0.004185,-0.008204,0.004350,0.009363,...,0.007905,0.003624,0.013501,0.016684,0.009069,-0.003798,0.003024,-0.000694,-0.012535,0.008915
125,2025-06-30,-0.009734,0.020340,0.018156,-0.016206,0.011609,0.002721,0.004473,0.016312,0.012688,...,0.010517,0.007799,0.002453,0.005243,0.004721,-0.014445,0.008812,-0.001550,-0.002733,-0.001409
126,2025-07-31,-0.027446,-0.007080,-0.001532,-0.017365,-0.025182,-0.017335,-0.028039,-0.004631,-0.000971,...,-0.007874,-0.014062,-0.014408,0.003996,0.014505,-0.002324,0.107351,-0.019321,-0.017895,-0.020294

In [ ]:
port_analysis = return_monthly.merge(top_columns, left_on = 'Date', right_index = True).reset_index()
port_analysis['prev_top_10'] = port_analysis['top_10'].shift(1)
port_analysis['prev_bot_10'] = port_analysis['bottom_10'].shift(1)
port_analysis
monthly_port_returns = []
for index, row in port_analysis[1:].iterrows():
  returns = []
  for stock in row['prev_top_10']:
    ret = row[stock]
    returns.append(ret)
  returns_array = np.array(returns)
  monthly_port_return = returns_array.sum()
  monthly_port_returns.append(monthly_port_return)
monthly_port_returns = np.array(monthly_port_returns)

cum_returns = (1+monthly_port_returns).cumprod()[-1]
cum_returns

np.float64(1.615968430683709)

In [ ]:
sharpe_ratio = (monthly_port_returns.mean()/monthly_port_returns.std())*np.sqrt(12)
sharpe_ratio

np.float64(0.7084442846471573)